#! /bin/sh
# chkconfig: 345 95 5
# description: otpsetup-controller
# processname: otpsetup-controller

case "$1" in
    start)
        cd /var/otp/OTPSetup/otpsetup/init_resources
        python init_settings.py

        cd /var/otp/OTPSetup
        export DJANGO_SETTINGS_MODULE=otpsetup.settings
        screen -d -m -L python -m otpsetup.transloader.main
        screen -d -m -L python -m otpsetup.controller_consumer.main
        
        cd /var/otp/OTPSetup/otpsetup
        screen -d -m -L python manage.py runserver 10.0.0.12:80

        exit 0
        ;;
esac

