#! /bin/sh
# /etc/init.d/otpsetup-proxy
#
### BEGIN INIT INFO
# Provides:          otpsetup-proxy
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:
# Default-Stop:
# Short-Description: Start otpsetup-proxy
# Description:       Start the OTPSetup proxy server module
### END INIT INFO

case "$1" in
    start)
        cd /var/otp/OTPSetup/otpsetup/init_resources
        python init_settings.py
        cd /var/otp/OTPSetup
        export DJANGO_SETTINGS_MODULE=otpsetup.settings
        python -m otpsetup.proxy_consumer.main &

        exit 0
        ;;
esac

